### ISSUE TITLE
Heat Map functionality broken

### ISSUE THREAD

**Issue by ColeTown** [A3M4/YouTube-Report#8] opened 2019-12-14 23:21 UTC
While running the script there is an issue with the heatmap where all values are set to zero for some reason. Not sure if that is how it supposed on the console, however, the end result shows this as well with each time 'block' set to the blue color for 0.  Not sure about where the problem is.
![image](https://user-images.githubusercontent.com/33290898/70855667-387e0f00-1e94-11ea-9929-4b2705b1afe0.png)
![image](https://user-images.githubusercontent.com/33290898/70855774-0077cb80-1e96-11ea-985c-e493c15fc670.png)

**Comment by oskarhertzman** [comment] 2019-12-15 01:34
Same here

**Comment by A3M4** [comment] 2019-12-15 01:54
I think this is caused by the different format of timezone in your takeout data, it is not fixed with e75b5f5, Can you check if it works for you now?
<img src="https://i.ibb.co/hLNRqY6/heat.png" alt="avatar" style="zoom: 200%;" />

**Closed** 2019-12-17 12:27 UTC
